---

  - name: Add the users for Rootless Podman
    usermod --add-subuids 100000-165535 --add-subgids 100000-165535 username

  - name: Install Archlinux Podman Image
    containers.podman.podman_image:
      name: archlinux

